version: '9.3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=work_accounting_db'
      - 'POSTGRES_PASSWORD=NiKiTaPaR'
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'spring-work-app'
    ports:
      - 8080:8080
    depends_on:
      - postgres
